[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy.envs]
JWT_SECRET = "ohLqK6kKpIAt"
SIG_KEY = "02A4UFhR3oXCVYFQ4b5tCh6hVq4e2ALX"
SIG_SALT = "PD7ZpSbskNaEUY9h3yctGi77ivqluPRj"
LLM_PROVIDER = "openai"
OPEN_MODEL_PREF = "gpt-4o"
VECTOR_DB = "pgvector"
INSTANCE_NAME = "MATI"
NODE_ENV = "production"
DATABASE_URL = "${POSTGRESQL_URL}"

[[services]]
name = "web"
port = 3001
internal_port = 3001

[logging]
level = "info"
format = "json"
